/**
 * @file MyKadResult.h
 *
 * Copyright (c)2017 Microblink Ltd. All rights reserved.
 *
 * ANY UNAUTHORIZED USE OR SALE, DUPLICATION, OR DISTRIBUTION
 * OF THIS PROGRAM OR ANY OF ITS PARTS, IN SOURCE OR BINARY FORMS,
 * WITH OR WITHOUT MODIFICATION, WITH THE PURPOSE OF ACQUIRING
 * UNLAWFUL MATERIAL OR ANY OTHER BENEFIT IS PROHIBITED!
 * THIS PROGRAM IS PROTECTED BY COPYRIGHT LAWS AND YOU MAY NOT
 * REVERSE ENGINEER, DECOMPILE, OR DISASSEMBLE IT.
 */

#ifndef MY_KAD_RESULT_INCLUDED
#define MY_KAD_RESULT_INCLUDED

#include "Recognizer/Export.h"
#include "Recognizer/RecognizerError.h"
#include "Recognizer/RecognizerResultFwd.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @struct MyKadResult
 * @brief Structure that holds result from scanning Malaysian ID card
 */
struct MyKadResult {
    /** NRIC number of the document holder */
    const char* nricNumber;

    /** Full name of the document holder */
    const char* fullName;

    /** Address of the document holder */
    const char* fullAddress;

    /** Street address of the document holder */
    const char* streetAddress;

    /** ZIP code of the document holder */
    const char* zipCode;

    /** City of the document holder */
    const char* city;

    /** State where document holder lives */
    const char* state;

    /** Religion of the document holder */
    const char* religion;

    /** Sex of the document holder */
    const char* sex;

    /** Date of birth of document holder in format YYMMDD */
    const char* dateOfBirth;
};

/**
 * @brief Typedef for MyKadResult structure.
 */
MB_EXPORTED_TYPE typedef struct MyKadResult MyKadResult;

/**
* @memberof RecognizerResult
* @brief Returns non-zero value if given result is generated by Malaysian ID card recognizer.
* @param result RecognizerResult object
* @return non-zero value if result is non-NULL and generated by Malaysian ID card recognizer, zero otherwise
*/
MB_API int MB_CALL recognizerResultIsMyKadResult( const RecognizerResult* result );

/**
* @memberof RecognizerResult
* @brief Obtains the scanned data from Malaysian ID document.
* @param result RecognizerResult object which stores the values of the results
* @param myKadResult Pointer to MyKadResult structure that will be filled with scanned data. All pointers within structure will be valid unti recognizerResultDelete is called on RecognizerResult object.
* @return status of the operation: RECOGNIZER_ERROR_STATUS_SUCCESS if everything is OK, RECOGNIZER_ERROR_STATUS_POINTER_IS_NULL if NULL is given as parameter,
*         RECOGNIZER_ERROR_STATUS_INVALID_TYPE if result is not a MyKad result.
*/
MB_API RecognizerErrorStatus MB_CALL recognizerResultGetMyKadResult( const RecognizerResult* result, MyKadResult* myKadResult );

#ifdef __cplusplus
}
#endif

#endif
