/**
 * @file IKadResult.h
 *
 * Copyright (c)2017 Microblink Ltd. All rights reserved.
 *
 * ANY UNAUTHORIZED USE OR SALE, DUPLICATION, OR DISTRIBUTION
 * OF THIS PROGRAM OR ANY OF ITS PARTS, IN SOURCE OR BINARY FORMS,
 * WITH OR WITHOUT MODIFICATION, WITH THE PURPOSE OF ACQUIRING
 * UNLAWFUL MATERIAL OR ANY OTHER BENEFIT IS PROHIBITED!
 * THIS PROGRAM IS PROTECTED BY COPYRIGHT LAWS AND YOU MAY NOT
 * REVERSE ENGINEER, DECOMPILE, OR DISASSEMBLE IT.
 */

#ifndef IKAD_RESULT_INCLUDED
#define IKAD_RESULT_INCLUDED

#include "Recognizer/Export.h"
#include "Recognizer/RecognizerError.h"
#include "Recognizer/RecognizerResultFwd.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @memberof RecognizerResult
 * @brief Returns non-zero value if given result is generated by Malaysian Immigrator ID card recognizer.
 * @param result RecognizerResult object
 * @return non-zero value if result is generated by Malaysian Immigrator ID card recognizer, zero otherwise
 */
MB_API int MB_CALL recognizerResultIsIKadResult( const RecognizerResult* result );

/**
 * @struct IKadResult
 * @brief Structure that holds result from scanning Malaysian Immigrator ID card
 */
struct IKadResult {
    /** Name of the document holder */
    const char* name;

    /** Passport number of the document holder */
    const char* passportNumber;

    /** Nationality of the document holder */
    const char* nationality;

    /** Date of birth of the document holder */
    MBDate dateOfBirth;

    /** Sex of the document holder */
    const char* sex;

    /** Sector in which document holder works */
    const char* sector;

    /** Employer of the document holder */
    const char* employer;

    /** Address of the document holder */
    const char* address;

    /** Date of expiry of the document */
    MBDate dateOfExpiry;
};

/**
 * @brief Typedef for IKadResult structure.
 */
MB_EXPORTED_TYPE typedef struct IKadResult IKadResult;

/**
* @memberof RecognizerResult
* @brief Obtains the scanned data from Malaysian Immigrator ID document.
* @param result RecognizerResult object which stores the values of the results
* @param iKadResult Pointer to IKadResult structure that will be filled with scanned data. All pointers within structure will be valid unti recognizerResultDelete is called on RecognizerResult object.
* @return status of the operation.
*/
MB_API RecognizerErrorStatus MB_CALL recognizerResultGetIKadResult( const RecognizerResult* result, IKadResult* iKadResult );

#ifdef __cplusplus
}
#endif

#endif
